# Generated by Django 4.1.3 on 2025-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Reader')], default=2, null=True),
        ),
    ]
